language: cpp
compiler: gcc
sudo: required

services:
- docker

before_install:
- docker pull filcuc/dotherside

script:
- docker run -v `pwd`:/root/dotherside filcuc/dotherside /bin/bash /root/build.sh ${COVERALLS_REPO_TOKEN}
