language: cpp
compiler: gcc
sudo: required

services:
- docker

before_install:
- docker pull filcuc/dotherside

install:
- gem install coveralls-lcov

script:
- ls
- docker run filcuc/dotherside /bin/bash /root/build.sh
