language: cpp
compiler: gcc
sudo: required

services:
- docker

before_install:
- docker pull filcuc/dotherside

install:
- gem install coveralls-lcov

script:
- docker run -v `pwd`:/root/dotherside filcuc/dotherside /bin/bash /root/build.sh
- coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} coverage.info
