name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build dependencies
      run: sudo apt-get -y update && sudo apt-get install -y qt5-default qtdeclarative5-dev qtquickcontrols2-5-dev qtbase5-dev cmake build-essential 
    - name: compile
      run: mkdir build && cd build && cmake -GNinja -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . 
    - name: test
      run: ./test/TestDynamicQObject  
    
