name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install qt
      run: sudo apt-get -y update && sudo apt-get install -y qt5-default qtdeclarative5-dev qtdeclarative5-private-dev qtbase5-dev cmake build-essential
    
