name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install qt
      run: apt-get update && apt-get install qt5-default qtdeclarative5-dev qtdeclarative5-private-dev qtbase-dev
    
